import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
const [root,dir]=process.argv.slice(2);
const imp=n=>import(pathToFileURL(path.join(root,'lib',n+'.ts')));
const {createTelegramSendQueue,withTelegramSendContext,getTelegramSendCorrelation,parseTelegramSendCorrelation}=await imp('send-queue');
const hash=t=>createHash('sha256').update(t).digest('hex');
let scope={profile:'fake',token:'fixture',ownerEpoch:1,pairedUserId:123},targetIdentity='one',calls=0,clock=0;
const q=createTelegramSendQueue({directory:dir,getScope:()=>scope,getTargetIdentity:()=>targetIdentity,record:()=>{},intervalMs:0,now:()=>clock,sleep:async ms=>{clock+=ms}});
const context=(extra={})=>({priority:'background',isActive:()=>true,activityId:'session:request-1',requestId:'request-1',route:'assistant-output',source:'autonomous',placement:'intermediate',replyIntent:hash('completion'),...extra});
const body={chat_id:123,text:'completion'};
const send=(c={},b=body,fn=async()=>({message_id:++calls}),method='sendMessage')=>withTelegramSendContext(context(c),()=>q.run(method,b,fn));
const ledger=()=>fs.readFileSync(path.join(dir,'delivery-ledger.jsonl'),'utf8').trim().split('\n').map(JSON.parse);
const done=[];
let release;const slow=async()=>{calls++;return new Promise(r=>release=()=>r({message_id:1}))};
const a=send({},body,slow);const b=send({placement:'terminal-partial'});assert.equal(calls,1);release();assert.deepEqual(await a,await b);const rows=ledger().length;
assert.equal((await send({placement:'final'})).message_id,1);assert.equal(calls,1);assert.equal(ledger().length,rows);assert.equal(ledger().filter(r=>r.status==='success').length,1);done.push('overlap_join_and_success_reuse_no_forged_receipt');
for(const c of [{activityId:'other-session:request-1'},{activityId:'session:request-2',requestId:'request-2'},{replyIntent:hash('different original intent')},{route:'queue',placement:'final'},{replyPart:1}])await send(c);
for(const b of [{...body,message_thread_id:2},{...body,reply_parameters:{message_id:80}},{...body,parse_mode:'HTML'},{...body,text:'different'}])await send({},b);
assert.equal(calls,10);done.push('new_session_request_intent_thread_quote_format_payload_and_part');
for(const method of ['editMessageText','sendMessageDraft','sendPhoto','sendDocument']){await send({},body,undefined,method);await send({},body,undefined,method)}assert.equal(calls,18);done.push('edits_previews_media_attachments_unchanged');
for(let i=0;i<2;i++)await withTelegramSendContext(context({activityId:'multipart'}),async()=>{await q.run('sendMessage',body,async()=>({message_id:++calls}));await q.run('sendMessage',body,async()=>({message_id:++calls}))});assert.equal(calls,20);done.push('identical_multipart_chunks_preserved_by_ordinal');
const fail=Object.assign(new Error('definite'),{status:400});let failCalls=0;await assert.rejects(()=>send({activityId:'failed'},body,async()=>{failCalls++;throw fail}));await send({activityId:'failed'},body,async()=>{failCalls++;return {message_id:500}});assert.equal(failCalls,2);done.push('known_failure_allows_new_attempt');
for(const err of [Object.assign(new Error('unknown'),{name:'TelegramApiCommitUnknownError'}),new Error('lost response'),Object.assign(new Error('server'),{status:503})]){
 const id=hash(err.message);let attempts=0;const work=()=>send({activityId:id},body,async()=>{attempts++;throw err});await assert.rejects(work);await assert.rejects(work);assert.equal(attempts,1);
}done.push('unknown_network_server_ack_held');
let missing=0;for(let i=0;i<2;i++)await assert.rejects(()=>send({activityId:'missing-receipt'},body,async()=>{missing++;return {ok:true}}),{name:'TelegramApiCommitUnknownError'});assert.equal(missing,1);assert(!ledger().some(r=>r.activity_id==='missing-receipt'&&r.status==='success'));done.push('missing_receipt_never_success');
let rates=0;const limited=()=>send({activityId:'rate'},body,async()=>{rates++;if(rates===1)throw Object.assign(new Error('429'),{status:429,retryAfterSeconds:900});return {message_id:501}});await Promise.all([limited(),limited()]);assert.equal(rates,2);assert(clock>=900000);done.push('long_cooldown_429_one_reserved_retry');
await assert.rejects(()=>send({isActive:()=>false}));targetIdentity='two';await send();scope={...scope,ownerEpoch:2};await send();scope={...scope,profile:'other'};await send();done.push('authority_fence_target_epoch_profile_changes');
const serialized=withTelegramSendContext(context(),()=>[getTelegramSendCorrelation(),getTelegramSendCorrelation()]);assert.deepEqual(serialized.map(c=>c.replyPart),[0,1]);assert.equal(parseTelegramSendCorrelation(serialized[0]).replyIntent,hash('completion'));assert.equal(parseTelegramSendCorrelation({replyIntent:'bad',replyPart:-1}).replyIntent,undefined);done.push('bus_allowlist_hash_and_part');
assert(!fs.readFileSync(path.join(dir,'delivery-ledger.jsonl'),'utf8').includes('"text":'));assert(ledger().some(r=>r.hash===hash(JSON.stringify('completion'))));done.push('ledger_payload_hash_semantics_preserved');
console.log(JSON.stringify({passed:done,real_api_calls:0}));
